function developerAudioPanelHtml(){return `<section class="devView" data-dev-view="audio">
        <div class="devSection"><div class="devSectionTitle">Audio Library</div><div id="devAudioSummary" class="devHint"></div><div class="devImportBar"><label>Import As<select id="devAudioImportCategory"><option value="sfx">Sound Effects</option><option value="music">Music</option><option value="ambience">Ambience</option><option value="ui">UI Sounds</option></select></label><button id="devAudioImport" class="primary">Choose Audio Files…</button></div><input id="devAudioImportFile" type="file" multiple accept="audio/mpeg,audio/ogg,audio/wav,.mp3,.ogg,.wav" hidden><div class="devHint">Batch import MP3, OGG, or WAV. Music/ambience loop by default; SFX/UI are one-shot. Audio is cached only when used.</div></div>
        <div class="devMasterDetail audioLayout">
          <div class="devMasterPane"><div class="devSection"><div class="devSectionTitle">Clips</div><div class="devPair"><input id="devAudioSearch" class="devSearchInput" placeholder="Search audio…"><select id="devAudioFilter"><option value="all">All Audio</option><option value="music">Music</option><option value="ambience">Ambience</option><option value="sfx">Sound Effects</option><option value="ui">UI</option></select></div><div id="devAudioList"></div></div></div>
          <div class="devDetailPane"><div class="devSection"><div class="devSectionTitle">Selected Clip</div><div id="devAudioInspector"></div></div></div>
        </div>
        <div class="devMasterDetail audioLayout">
          <div class="devMasterPane"><div class="devSection"><div class="devSectionTitle">Sound Sets</div><div class="devHint">Group variations such as grass-step-1/2/3 into one reusable set. Terrain footsteps select these sets.</div><button id="devAudioNewSet" class="devWideButton primary">New Sound Set</button><div id="devAudioSetList"></div></div></div>
          <div class="devDetailPane"><div class="devSection"><div class="devSectionTitle">Sound Set Inspector</div><div id="devAudioSetInspector"></div></div></div>
        </div>
        <div class="devSection"><div class="devSectionTitle">Active Zone Music & Ambience</div><div id="devZoneAudio"></div></div>
        <div class="devSection" data-default-collapsed="true"><div class="devSectionTitle">Game Sound Events</div><div class="devHint">Engine events are generic; the project chooses the clip/set that plays.</div><div id="devAudioEvents"></div></div>
      </section>`;}
// Builder Audio Library ------------------------------------------------------
let devAudioPreviewHandle=null;
const DEV_AUDIO_CATEGORY_LABELS={music:"Music",ambience:"Ambience",sfx:"Sound Effects",ui:"UI"};
const DEV_AUDIO_EVENT_LABELS={questAccept:"Quest Accepted",playerAttack:"Player Attack",playerHit:"Player Hit",potion:"Potion",lootPickup:"Loot Pickup",questTurnIn:"Quest Complete",levelUp:"Level Up"};
function developerAudioSyncRuntime(){window.LR_AUDIO_CLIPS=devAudioClips;window.LR_AUDIO_SETS=devAudioSets;window.LR_AUDIO_EVENTS=devAudioEvents;if(window.LR_SHARED_CONTENT){window.LR_SHARED_CONTENT.audioClips=devAudioClips;window.LR_SHARED_CONTENT.audioSets=devAudioSets;window.LR_SHARED_CONTENT.audioEvents=devAudioEvents;}}
function developerAudioRefOptions(selected="",{category="",includeSets=false,empty="None"}={}){
  const rows=[`<option value="" ${selected?"":"selected"}>${devContentEscape(empty)}</option>`];
  for(const [id,clip] of Object.entries(devAudioClips||{}).sort((a,b)=>String(a[1]?.name||a[0]).localeCompare(String(b[1]?.name||b[0])))){
    if(category&&clip?.category!==category)continue;rows.push(`<option value="${devContentEscape(id)}" ${id===selected?"selected":""}>${devContentEscape(clip?.name||id)} • ${devContentEscape(DEV_AUDIO_CATEGORY_LABELS[clip?.category]||clip?.category||"Audio")}</option>`);
  }
  if(includeSets)for(const [id,set] of Object.entries(devAudioSets||{}).sort((a,b)=>String(a[1]?.name||a[0]).localeCompare(String(b[1]?.name||b[0]))))rows.push(`<option value="${devContentEscape(id)}" ${id===selected?"selected":""}>Set • ${devContentEscape(set?.name||id)}</option>`);
  return rows.join("");
}
function developerAudioUniqueId(base,library=devAudioClips){const root=devContentId(base,"audio");let id=root,n=2;while(library[id])id=`${root}-${n++}`;return id;}
function developerAudioStopPreview(){if(devAudioPreviewHandle){stopAudioHandle(devAudioPreviewHandle,.08);devAudioPreviewHandle=null;}}
async function developerAudioPreview(id){developerAudioStopPreview();developerAudioSyncRuntime();await unlockAudio();const set=devAudioSets?.[id];devAudioPreviewHandle=set?await playAudioSet(id,{bus:"sfx",volume:.8}):await playAudioClip(id,{bus:audioBusForClip(id),volume:.8});if(!devAudioPreviewHandle)devSetStatus(`Could not preview audio: ${id}`);}
function developerAudioClipInspector(id,clip){
  if(!id||!clip)return '<div class="devEmpty">Select an audio clip.</div>';
  return `<div class="devSelectedTitle">${devContentEscape(clip.name||id)}</div><div class="devHint">${devContentEscape(clip.path||"")}</div>
    <div class="devPair"><label>Name<input id="devAudioClipName" value="${devContentEscape(clip.name||id)}"></label><label>Category<select id="devAudioClipCategory">${Object.entries(DEV_AUDIO_CATEGORY_LABELS).map(([v,l])=>`<option value="${v}" ${clip.category===v?"selected":""}>${l}</option>`).join("")}</select></label></div>
    <div class="devPair"><label>Default Volume %<input id="devAudioClipVolume" type="number" min="0" max="200" value="${Math.round(numberOr(clip.volume,1)*100)}"></label><label><span>Loop by Default</span><span class="devInlineCheck"><input id="devAudioClipLoop" type="checkbox" ${clip.loop?"checked":""}> Loop</span></label></div>
    <div class="devRow"><button id="devAudioPreviewClip" class="primary">▶ Preview</button><button id="devAudioStopClip">■ Stop</button><button id="devAudioSaveClip">Save Clip</button><button id="devAudioDeleteClip" class="danger">Delete</button></div>`;
}
function developerAudioSetInspector(id,set){
  if(!id||!set)return '<div class="devEmpty">Create or select a sound set. Terrain footsteps use sound sets so each step can randomly vary.</div>';
  const checks=Object.entries(devAudioClips||{}).filter(([,c])=>c?.category==="sfx").sort((a,b)=>String(a[1]?.name||a[0]).localeCompare(String(b[1]?.name||b[0]))).map(([clipId,clip])=>`<label class="devAudioClipCheck"><input type="checkbox" data-audio-set-clip="${devContentEscape(clipId)}" ${(set.clipIds||[]).includes(clipId)?"checked":""}><span>${devContentEscape(clip.name||clipId)}</span><button type="button" data-audio-preview="${devContentEscape(clipId)}">▶</button></label>`).join("")||'<div class="devEmpty">Import Sound Effects first.</div>';
  return `<div class="devSelectedTitle">SOUND SET • ${devContentEscape(set.name||id)}</div><div class="devPair"><label>Name<input id="devAudioSetName" value="${devContentEscape(set.name||id)}"></label><label>Set Volume %<input id="devAudioSetVolume" type="number" min="0" max="200" value="${Math.round(numberOr(set.volume,1)*100)}"></label></div><div class="devHint">Select multiple related variations. Footsteps will rotate/randomize through these clips rather than repeating one identical sound.</div><div class="devAudioSetClips">${checks}</div><div class="devRow"><button id="devAudioPreviewSet" class="primary">▶ Preview Set</button><button id="devAudioSaveSet">Save Set</button><button id="devAudioDeleteSet" class="danger">Delete Set</button></div>`;
}
function developerCreateAudioSet(){const id=developerAudioUniqueId("new-sound-set",devAudioSets);devAudioSets[id]={name:"New Sound Set",clipIds:[],volume:1};devAudioSelectedSetId=id;devAudioLibraryMode="sets";developerAudioSyncRuntime();saveDeveloperDraft();refreshDeveloperAudioPanel();}
function developerSaveAudioClip(){const id=devAudioSelectedId,clip=devAudioClips?.[id],root=devPanel?.querySelector("#devAudioInspector");if(!clip||!root)return;clip.name=String(root.querySelector("#devAudioClipName")?.value||id).trim()||id;clip.category=root.querySelector("#devAudioClipCategory")?.value||"sfx";clip.volume=Math.max(0,Math.min(2,numberOr(root.querySelector("#devAudioClipVolume")?.value,100)/100));clip.loop=!!root.querySelector("#devAudioClipLoop")?.checked;developerAudioSyncRuntime();saveDeveloperDraft();refreshDeveloperAudioPanel();devSetStatus(`Saved audio clip: ${clip.name}`);}
function developerDeleteAudioClip(){const id=devAudioSelectedId,clip=devAudioClips?.[id];if(!clip||!confirm(`Delete audio record '${clip.name||id}'? The file will remain in the project folder.`))return;delete devAudioClips[id];for(const set of Object.values(devAudioSets||{}))set.clipIds=(set.clipIds||[]).filter(v=>v!==id);for(const [key,value] of Object.entries(devAudioEvents||{}))if(value===id)devAudioEvents[key]="";for(const t of Object.values(devTerrains||{}))if(t.footstepSet===id)t.footstepSet="";devAudioSelectedId=Object.keys(devAudioClips)[0]||null;developerAudioSyncRuntime();saveDeveloperDraft();refreshDeveloperPanel();}
function developerSaveAudioSet(){const id=devAudioSelectedSetId,set=devAudioSets?.[id],root=devPanel?.querySelector("#devAudioSetInspector");if(!set||!root)return;set.name=String(root.querySelector("#devAudioSetName")?.value||id).trim()||id;set.volume=Math.max(0,Math.min(2,numberOr(root.querySelector("#devAudioSetVolume")?.value,100)/100));set.clipIds=Array.from(root.querySelectorAll("[data-audio-set-clip]:checked")).map(el=>el.dataset.audioSetClip).filter(id=>devAudioClips[id]);developerAudioSyncRuntime();saveDeveloperDraft();refreshDeveloperAudioPanel();devSetStatus(`Saved sound set: ${set.name}`);}
function developerDeleteAudioSet(){const id=devAudioSelectedSetId,set=devAudioSets?.[id];if(!set||!confirm(`Delete sound set '${set.name||id}'?`))return;delete devAudioSets[id];for(const t of Object.values(devTerrains||{}))if(t.footstepSet===id)t.footstepSet="";for(const [key,value] of Object.entries(devAudioEvents||{}))if(value===id)devAudioEvents[key]="";devAudioSelectedSetId=Object.keys(devAudioSets)[0]||null;developerAudioSyncRuntime();saveDeveloperDraft();refreshDeveloperPanel();}
function developerSaveZoneAudio(){const root=devPanel?.querySelector("#devZoneAudio");if(!root)return;const z=window.LR_ZONE_SETTINGS||(window.LR_ZONE_SETTINGS={});z.musicId=root.querySelector("#devZoneMusic")?.value||"";z.musicVolume=Math.max(0,Math.min(2,numberOr(root.querySelector("#devZoneMusicVolume")?.value,100)/100));z.ambienceId=root.querySelector("#devZoneAmbience")?.value||"";z.ambienceVolume=Math.max(0,Math.min(2,numberOr(root.querySelector("#devZoneAmbienceVolume")?.value,100)/100));applyZoneAudioFromCurrentSettings();saveDeveloperDraft();devSetStatus("Zone audio updated");}
function developerSaveAudioEvents(){const root=devPanel?.querySelector("#devAudioEvents");if(!root)return;for(const key of Object.keys(DEV_AUDIO_EVENT_LABELS))devAudioEvents[key]=root.querySelector(`[data-audio-event="${key}"]`)?.value||"";developerAudioSyncRuntime();saveDeveloperDraft();devSetStatus("Game sound events updated");}
function refreshDeveloperAudioPanel(){
  if(!devPanel)return;developerAudioSyncRuntime();const list=devPanel.querySelector("#devAudioList"),inspector=devPanel.querySelector("#devAudioInspector"),setList=devPanel.querySelector("#devAudioSetList"),setInspector=devPanel.querySelector("#devAudioSetInspector"),summary=devPanel.querySelector("#devAudioSummary");if(!list)return;
  const q=String(devPanel.querySelector("#devAudioSearch")?.value||"").trim().toLowerCase(),filter=devPanel.querySelector("#devAudioFilter")?.value||"all",entries=Object.entries(devAudioClips||{}).filter(([id,c])=>(filter==="all"||c.category===filter)&&(!q||`${c.name||""} ${id}`.toLowerCase().includes(q))).sort((a,b)=>String(a[1]?.name||a[0]).localeCompare(String(b[1]?.name||b[0])));
  if(!devAudioSelectedId||!devAudioClips[devAudioSelectedId])devAudioSelectedId=entries[0]?.[0]||Object.keys(devAudioClips)[0]||null;
  list.innerHTML=entries.map(([id,c])=>`<button class="devAudioCard ${id===devAudioSelectedId?"active":""}" data-audio-id="${devContentEscape(id)}"><span class="devAudioIcon">${c.category==="music"?"♫":c.category==="ambience"?"≈":c.category==="ui"?"◈":"♪"}</span><span><b>${devContentEscape(c.name||id)}</b><small>${devContentEscape(DEV_AUDIO_CATEGORY_LABELS[c.category]||c.category||"Audio")}</small></span><span class="devAudioCardPlay" data-audio-preview="${devContentEscape(id)}">▶</span></button>`).join("")||'<div class="devEmpty">No audio clips match this filter.</div>';
  list.querySelectorAll("[data-audio-id]").forEach(btn=>btn.onclick=e=>{if(e.target.closest("[data-audio-preview]"))return;devAudioSelectedId=btn.dataset.audioId;refreshDeveloperAudioPanel();});list.querySelectorAll("[data-audio-preview]").forEach(btn=>btn.onclick=e=>{e.stopPropagation();developerAudioPreview(btn.dataset.audioPreview);});
  if(inspector){inspector.innerHTML=developerAudioClipInspector(devAudioSelectedId,devAudioClips?.[devAudioSelectedId]);inspector.querySelector("#devAudioPreviewClip")?.addEventListener("click",()=>developerAudioPreview(devAudioSelectedId));inspector.querySelector("#devAudioStopClip")?.addEventListener("click",developerAudioStopPreview);inspector.querySelector("#devAudioSaveClip")?.addEventListener("click",developerSaveAudioClip);inspector.querySelector("#devAudioDeleteClip")?.addEventListener("click",developerDeleteAudioClip);}
  const sets=Object.entries(devAudioSets||{}).sort((a,b)=>String(a[1]?.name||a[0]).localeCompare(String(b[1]?.name||b[0])));if(!devAudioSelectedSetId||!devAudioSets[devAudioSelectedSetId])devAudioSelectedSetId=sets[0]?.[0]||null;if(setList)setList.innerHTML=sets.map(([id,set])=>`<button class="devAudioSetCard ${id===devAudioSelectedSetId?"active":""}" data-audio-set-id="${devContentEscape(id)}"><b>${devContentEscape(set.name||id)}</b><small>${(set.clipIds||[]).length} variations</small></button>`).join("")||'<div class="devEmpty">No sound sets yet.</div>';setList?.querySelectorAll("[data-audio-set-id]").forEach(btn=>btn.onclick=()=>{devAudioSelectedSetId=btn.dataset.audioSetId;refreshDeveloperAudioPanel();});
  if(setInspector){setInspector.innerHTML=developerAudioSetInspector(devAudioSelectedSetId,devAudioSets?.[devAudioSelectedSetId]);setInspector.querySelectorAll("[data-audio-preview]").forEach(btn=>btn.onclick=e=>{e.preventDefault();developerAudioPreview(btn.dataset.audioPreview);});setInspector.querySelector("#devAudioPreviewSet")?.addEventListener("click",()=>developerAudioPreview(devAudioSelectedSetId));setInspector.querySelector("#devAudioSaveSet")?.addEventListener("click",developerSaveAudioSet);setInspector.querySelector("#devAudioDeleteSet")?.addEventListener("click",developerDeleteAudioSet);}
  const zoneRoot=devPanel.querySelector("#devZoneAudio");if(zoneRoot){const z=window.LR_ZONE_SETTINGS||{};zoneRoot.innerHTML=`<div class="devPair"><label>Music<select id="devZoneMusic">${developerAudioRefOptions(z.musicId||"",{category:"music",empty:"No music"})}</select></label><label>Music Volume %<input id="devZoneMusicVolume" type="number" min="0" max="200" value="${Math.round(numberOr(z.musicVolume,1)*100)}"></label></div><div class="devPair"><label>Ambience<select id="devZoneAmbience">${developerAudioRefOptions(z.ambienceId||"",{category:"ambience",empty:"No ambience"})}</select></label><label>Ambience Volume %<input id="devZoneAmbienceVolume" type="number" min="0" max="200" value="${Math.round(numberOr(z.ambienceVolume,1)*100)}"></label></div><div class="devRow"><button id="devZoneAudioSave" class="primary">Apply Zone Audio</button><button id="devZoneMusicPreview">▶ Music</button><button id="devZoneAmbiencePreview">▶ Ambience</button></div>`;zoneRoot.querySelector("#devZoneAudioSave").onclick=developerSaveZoneAudio;zoneRoot.querySelector("#devZoneMusicPreview").onclick=()=>developerAudioPreview(zoneRoot.querySelector("#devZoneMusic").value);zoneRoot.querySelector("#devZoneAmbiencePreview").onclick=()=>developerAudioPreview(zoneRoot.querySelector("#devZoneAmbience").value);}
  const eventsRoot=devPanel.querySelector("#devAudioEvents");if(eventsRoot){eventsRoot.innerHTML=Object.entries(DEV_AUDIO_EVENT_LABELS).map(([key,label])=>`<div class="devAudioEventRow"><label>${devContentEscape(label)}<select data-audio-event="${key}">${developerAudioRefOptions(devAudioEvents[key]||"",{includeSets:true})}</select></label><button data-audio-event-preview="${key}">▶</button></div>`).join("")+`<button id="devAudioEventsSave" class="devWideButton primary">Save Game Sound Events</button>`;eventsRoot.querySelector("#devAudioEventsSave").onclick=developerSaveAudioEvents;eventsRoot.querySelectorAll("[data-audio-event-preview]").forEach(btn=>btn.onclick=()=>{const key=btn.dataset.audioEventPreview,id=eventsRoot.querySelector(`[data-audio-event="${key}"]`)?.value;if(id)developerAudioPreview(id);});}
  if(summary)summary.textContent=`${Object.keys(devAudioClips).length} clips • ${Object.keys(devAudioSets).length} sound sets • ${Object.values(devAudioEvents).filter(Boolean).length} game events assigned`;
}
