const DEV_DRAFT_KEY = "littleRealmWorldBuilderDraft";
let devModeActive=false;
let devPanel=null;
let devSelected=null;
let devPlaceType=null;
let devDragging=false;
let devDragOffset={x:0,y:0};
let devHitboxEditing=false;
let devHitboxDrag=null;
let devDepthEditing=false;
let devDepthDrag=null;
let devInteractionEditing=false;
let devInteractionDrag=null;
let devSizeEditing=false;
let devSizeDrag=null;
let devShowGrid=true;
let devShowHitboxes=true;
let devShowDepthLines=true;
let devSnap=8;
let devStatusTimer=null;
let devSelectedMob=null;
let devSelectedNpc=null;
let devNpcDragging=false;
let devNpcDragOffset={x:0,y:0};
let devPlaceNpcAsset=null;
let devPlaceMobType=null;
let devSelectedSpawnId=null;
let devSpawnDragging=false;
let devSpawnDragOffset={x:0,y:0};
let devSelectedQuestId=null;
let devQuestFormDraft=null;
let devActiveTab="objects";
let devRepeatPlacement=false;
let devTabScrollPositions={};
let devCombatMobType=Object.keys(BALANCE.mobs||{})[0]||null;
let devPlayerTestBaseline=null;
let devSelectedRemnant=null;
let devRemnantPreview=null;
let devRemnantDragging=false;
let devRemnantDragOffset={x:0,y:0};
const DEV_PROJECT_BALANCE=JSON.parse(JSON.stringify(BALANCE));
let devProjectDirectoryHandle=null;
let devProjectManifest=(typeof window!=="undefined"?window.LR_BUILDER_PROJECT?.manifest:null)||null;
let devProjectZone=(typeof window!=="undefined"?window.LR_BUILDER_PROJECT?.zone:null)||null;
let devProjectSharedContentPath=(typeof window!=="undefined"?window.LR_BUILDER_PROJECT?.manifest?.sharedContent:null)||"content/shared/content-library.json";
let devZoneBaselinePack=JSON.parse(JSON.stringify((typeof window!=="undefined"?window.LR_BUILDER_PROJECT?.pack:null)||{}));
let devProjectSharedBaseline=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT)||{}));
let devZoneSelectedId=devProjectZone?.id||null;
const DEV_PROJECT_ITEMS=JSON.parse(JSON.stringify(ITEM_DEFS));
const DEV_PROJECT_LOOT_TABLES=JSON.parse(JSON.stringify(LOOT_TABLES));
const DEV_PROJECT_MOB_SPAWNS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_MOB_SPAWNS)||[]));
const DEV_PROJECT_ASSETS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_ASSETS)||{}));
const DEV_PROJECT_OBJECT_DEFINITIONS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_OBJECT_DEFINITIONS)||{}));
const DEV_PROJECT_TERRAINS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_TERRAINS)||{}));
const DEV_PROJECT_TERRAIN_DEFAULTS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_TERRAIN_DEFAULTS)||{}));
const DEV_PROJECT_ART_REFERENCES=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT?.artReferences)||{}));
const DEV_PROJECT_CHARACTER_DEFAULTS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT?.characterDefaults)||{}));
const DEV_PROJECT_AUDIO_CLIPS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT?.audioClips)||{}));
const DEV_PROJECT_AUDIO_SETS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT?.audioSets)||{}));
const DEV_PROJECT_AUDIO_EVENTS=JSON.parse(JSON.stringify((typeof window!=="undefined"&&window.LR_SHARED_CONTENT?.audioEvents)||{}));
let devMobSpawns=JSON.parse(JSON.stringify(DEV_PROJECT_MOB_SPAWNS));
let devAssets=JSON.parse(JSON.stringify(DEV_PROJECT_ASSETS));
let devObjectDefinitions=JSON.parse(JSON.stringify(DEV_PROJECT_OBJECT_DEFINITIONS));
let devTerrains=JSON.parse(JSON.stringify(DEV_PROJECT_TERRAINS));
let devTerrainDefaults=JSON.parse(JSON.stringify(DEV_PROJECT_TERRAIN_DEFAULTS));
let devArtReferences=JSON.parse(JSON.stringify(DEV_PROJECT_ART_REFERENCES));
let devCharacterDefaults=JSON.parse(JSON.stringify(DEV_PROJECT_CHARACTER_DEFAULTS));
let devAudioClips=JSON.parse(JSON.stringify(DEV_PROJECT_AUDIO_CLIPS));
let devAudioSets=JSON.parse(JSON.stringify(DEV_PROJECT_AUDIO_SETS));
let devAudioEvents=JSON.parse(JSON.stringify(DEV_PROJECT_AUDIO_EVENTS));
let devAudioSelectedId=Object.keys(devAudioClips)[0]||null;
let devAudioSelectedSetId=Object.keys(devAudioSets)[0]||null;
let devAudioLibraryMode="clips";
let devTerrainSelectedId=Object.keys(devTerrains)[0]||null;
let devAssetSelectedId=null;
let devArtPromptDraft={kind:"mob",sizeClass:"medium",subject:"",description:"",palette:"",constraints:""};
let devContentType="mobs";
let devContentSelectedId=null;
let devTerrainBrush=Object.keys(devTerrains)[0]||"";
let devTerrainBrushSize=1;
let devTerrainPainting=false;
let devTerrainDirty=false;
let devTerrainLastTileKey=null;
let devTerrainHoverTile=null;

// Builder-only camera state. Gameplay always returns to the normal player-follow camera.
let devCameraMode="player"; // player | free | world
let devCameraX=null;
let devCameraY=null;
let devCameraZoom=CAMERA_ZOOM;
let devCameraKeys={up:false,down:false,left:false,right:false};
let devCameraPanDrag=null;

