function ensureDeveloperStyles(){
  if(document.getElementById("littleRealmDevStyles")) return;
  const style=document.createElement("style");
  style.id="littleRealmDevStyles";
  style.textContent=`
    #devPanel{position:fixed!important;z-index:10000!important;top:12px!important;right:12px!important;width:min(880px,68vw)!important;height:min(860px,calc(100vh - 24px))!important;background:rgba(24,20,30,.98)!important;border:1px solid rgba(255,255,255,.22)!important;border-radius:16px!important;box-shadow:0 18px 50px rgba(0,0,0,.55)!important;color:#f8f2ff!important;display:none!important;overflow:hidden!important;font:13px system-ui,sans-serif!important;backdrop-filter:blur(8px)!important}
    #devPanel.show{display:flex!important;flex-direction:column!important}
    #devPanel *{box-sizing:border-box}
    #devPanel .devHeader{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;background:#453552;border-bottom:1px solid rgba(255,255,255,.12)}
    #devPanel .devHeader b{display:block;font-size:15px;letter-spacing:.08em} #devPanel .devHeader span{display:block;font-size:11px;color:#cdbed9;margin-top:2px}
    #devPanel button,#devPanel select,#devPanel input{font:inherit}
    #devPanel .devHeader button{width:36px;height:36px;border:0;border-radius:9px;background:#2a2132;color:white;font-size:22px}
    #devPanel .devToolbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap;padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.1)}
    #devPanel .devToolbar button,#devPanel .devToolbar select,#devPanel .devProjectActions button,#devPanel .devRow button,#devPanel .devMobTypeChip{border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:8px 10px;font-weight:700}
    #devPanel .devToolbar button.active,#devPanel .devPropButton.active,#devPanel .devTab.active,#devPanel .devMobTypeChip.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel .devToolbar label{display:flex;gap:5px;align-items:center;color:#e5d9ec}
    #devPanel .devTabs{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;padding:8px 12px;border-bottom:1px solid rgba(255,255,255,.1);background:#211a28}
    #devPanel .devTab{border:1px solid rgba(255,255,255,.12);background:#30283a;color:#d9cfdf;border-radius:9px;padding:9px 10px;font-weight:800;cursor:pointer}

    #devPanel .devContextBar{display:flex;align-items:center;gap:8px;padding:7px 12px;background:#18141d;border-bottom:1px solid rgba(255,255,255,.1)}
    #devPanel .devToolMode{flex:1;min-width:0;border:1px solid rgba(255,255,255,.1);background:#2a2331;border-radius:8px;padding:7px 9px;font-size:11px;font-weight:900;letter-spacing:.03em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#d8cfe0}
    #devPanel .devToolMode.place{background:#493f24;border-color:#8d7837;color:#ffe8a2} #devPanel .devToolMode.paint{background:#25474d;border-color:#4d8893;color:#bdf5ff} #devPanel .devToolMode.edit{background:#473254;border-color:#77518d;color:#f0cfff}
    #devPanel .devRepeatPlacement{display:flex;align-items:center;gap:5px;color:#d5c9dc;font-size:11px;white-space:nowrap;user-select:none} #devPanel .devRepeatPlacement input{accent-color:#63e6ff}
    #devPanel #devFinishTool{border:1px solid rgba(255,255,255,.14);background:#4f405c;color:#fff;border-radius:8px;padding:7px 9px;font-weight:850;white-space:nowrap}
    #devPanel .devSectionNav{display:flex;gap:5px;overflow-x:auto;padding:6px 12px;background:#201a26;border-bottom:1px solid rgba(255,255,255,.08);scrollbar-width:thin}
    #devPanel .devSectionJump{flex:0 0 auto;border:1px solid rgba(255,255,255,.1);background:#2d2635;color:#cfc3d6;border-radius:999px;padding:5px 9px;font-size:10px;font-weight:800;cursor:pointer}
    #devPanel .devSectionJump:hover{background:#3d3248;color:#fff}
    #devPanel .devBody{flex:1;min-height:0;overflow:auto;padding:12px;scroll-behavior:smooth}
    #devPanel .devView{display:none}#devPanel .devView.active{display:block}
    #devPanel .devSection{background:#241e2b;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px;margin-bottom:12px}
    #devPanel .devSectionTitle{padding:0 2px 8px;font-weight:900;color:#d8c1e7;letter-spacing:.06em;text-transform:uppercase;font-size:12px}
    #devPanel .devHint{color:#b9aebe;font-size:11px;margin:-2px 2px 9px;line-height:1.35}
    #devPanel #devObjectPalette{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:7px!important;max-height:360px!important;overflow:auto!important;padding:2px!important}
    #devPanel .devPropButton{min-width:0;border:1px solid rgba(255,255,255,.12);background:#30283a;color:#eee;border-radius:9px;padding:5px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer;min-height:76px}
    #devPanel .devPropButton canvas{width:52px;height:52px;image-rendering:pixelated;background:rgba(255,255,255,.025);border-radius:5px}
    #devPanel .devPropButton span{font-size:10px;line-height:1.05;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-transform:capitalize}
    #devPanel #devObjectList,#devPanel #devSelectionList{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;max-height:260px;overflow:auto}
    #devPanel .devObjectChip{border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:8px;padding:7px 9px;font-size:11px;cursor:pointer;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    #devPanel .devObjectChip.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel #devScalePanel{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}
    #devPanel .devScaleControl{background:#2b2432;border:1px solid rgba(255,255,255,.07);border-radius:10px;padding:10px;color:#ddd}
    #devPanel .devScaleControl .devScaleTop{display:flex;justify-content:space-between;gap:8px;font-size:11px;font-weight:800;margin-bottom:7px}
    #devPanel .devScaleControl input[type=range]{width:100%;accent-color:#63e6ff}
    #devPanel #devMobScalePanel{background:#2b2432;border:1px solid rgba(99,230,255,.18);border-radius:12px;padding:12px;min-height:130px}
    #devPanel .devMobSelectedTitle{font-size:18px;font-weight:900;color:#7ceaff;margin-bottom:3px}.devMobMeta{color:#bdb0c5;font-size:11px;margin-bottom:11px}
    #devPanel #devMobTypeChips{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.devMobTypeChip{font-size:10px!important;padding:6px 8px!important;cursor:pointer}
    #devPanel #devInspector{padding:2px;min-height:180px}
    #devPanel .devEmpty{color:#baaec2;padding:12px;background:#2b2432;border-radius:9px}.devSelectedTitle{font-size:16px;font-weight:900;margin-bottom:9px;color:#7ceaff;text-transform:capitalize}
    #devPanel #devInspector label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc}
    #devPanel #devInspector input[type=text],#devPanel #devInspector input[type=number],#devPanel #devInspector input:not([type]),#devPanel #devInspector select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px}
    #devPanel .devChecks{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px} #devPanel .devChecks label{flex-direction:row!important;align-items:center!important;background:#2b2432;padding:8px;border-radius:7px}
    #devPanel .devPair{display:grid;grid-template-columns:1fr 1fr;gap:9px} #devPanel .devQuad{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}
    #devPanel .devSubhead{font-weight:800;margin-top:10px;color:#c9b9d2} #devPanel .devRow{display:flex;gap:7px;margin-top:10px} #devPanel .devRow button{flex:1} #devPanel .devRow .danger{background:#713b47}
    #devPanel .devHitboxEditButton{width:100%;margin-top:8px;border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:9px 10px;font-weight:900;cursor:pointer}
    #devPanel .devHitboxEditButton.active{outline:2px solid #ffd166;background:#66532b;color:#fff8dd}
    #devPanel .devHitboxEditHelp{margin-top:7px;padding:8px 9px;border:1px solid rgba(255,209,102,.18);border-radius:8px;background:rgba(255,209,102,.06);color:#d8cdbc;font-size:10px;line-height:1.35}
    #devPanel .devDepthEditButton{width:100%;margin-top:8px;border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:9px 10px;font-weight:900;cursor:pointer}
    #devPanel .devDepthEditButton.active{outline:2px solid #d58cff;background:#59406a;color:#fff4ff}
    #devPanel .devDepthEditButton:disabled{opacity:.42;cursor:not-allowed}
    #devPanel .devDepthEditHelp{margin-top:7px;padding:8px 9px;border:1px solid rgba(213,140,255,.20);border-radius:8px;background:rgba(213,140,255,.07);color:#d8cdbc;font-size:10px;line-height:1.35}
    #devPanel .devProjectActions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px} #devPanel .devProjectActions button:first-child{grid-column:1/-1;background:#38606a}
    #devPanel #devStatus{padding:9px 12px;background:#1d1822;color:#bdb0c5;font-size:11px;border-top:1px solid rgba(255,255,255,.08)}

    #devPanel .devCombatGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}
    #devPanel .devCombatField{display:flex;flex-direction:column;gap:4px;color:#d7cbdc;font-size:11px;font-weight:700}
    #devPanel .devCombatField input,#devPanel .devCombatField select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px}
    #devPanel .devCombatCheck{display:flex;align-items:center;gap:7px;background:#2b2432;border-radius:8px;padding:9px;color:#ddd;font-weight:700}
    #devPanel .devCombatActions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.devCombatActions button{border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:8px 10px;font-weight:800;cursor:pointer}.devCombatActions .primary{background:#38606a}.devCombatActions .danger{background:#713b47}
    #devPanel .devCombatDetails{background:#211b27;border:1px solid rgba(255,255,255,.08);border-radius:10px;margin:8px 0;overflow:hidden}.devCombatDetails summary{cursor:pointer;padding:10px 11px;font-weight:900;color:#d8c1e7;user-select:none}.devCombatDetails>div{padding:0 10px 10px}
    #devPanel .devPlayerTest{display:grid;grid-template-columns:minmax(110px,160px) 1fr;gap:10px;align-items:end}.devQuickLevels{display:flex;gap:5px;flex-wrap:wrap}.devQuickLevels button{border:1px solid rgba(255,255,255,.12);background:#30283a;color:#fff;border-radius:7px;padding:7px 9px;font-weight:800}
    #devPanel .devStatPreview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:9px}.devStatPreview div{background:#2b2432;border-radius:8px;padding:8px;text-align:center}.devStatPreview b{display:block;color:#7ceaff;font-size:14px}.devStatPreview span{font-size:9px;color:#a99bb3;text-transform:uppercase;letter-spacing:.05em}
    #devPanel .devNpcPalette{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.devNpcPalette button{border:1px solid rgba(255,255,255,.12);background:#30283a;color:#fff;border-radius:9px;padding:9px;font-weight:850;cursor:pointer}.devNpcPalette button.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel #devNpcList,#devPanel #devQuestList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:230px;overflow:auto}.devNpcChip,.devQuestChip{border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:8px;padding:7px 9px;font-size:11px;cursor:pointer;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devNpcChip.active,.devQuestChip.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel .devNpcInspector label,#devPanel .devQuestEditor label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc;font-size:11px;font-weight:700}.devNpcInspector input,.devNpcInspector select,.devNpcInspector textarea,.devQuestEditor input,.devQuestEditor select,.devQuestEditor textarea{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit}.devNpcInspector textarea,.devQuestEditor textarea{min-height:62px;resize:vertical}
    #devPanel .devQuestObjective{margin-top:8px;padding:8px;border:1px solid rgba(255,255,255,.08);border-radius:9px;background:#2a2331}.devQuestObjectiveTop{display:grid;grid-template-columns:1fr 1.35fr .55fr auto;gap:6px;align-items:end}.devQuestObjectiveTop button{height:34px;border:1px solid rgba(255,255,255,.12);background:#713b47;color:#fff;border-radius:7px;font-weight:900}.devVisitGrid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.devQuestListActions{display:flex;gap:7px;margin-top:8px}.devQuestListActions button{flex:1;border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:8px;font-weight:800}
    #devPanel .devProjectBig{display:grid;grid-template-columns:1fr 1fr;gap:8px}.devProjectBig button{border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:9px;padding:10px;font-weight:850}.devProjectBig .primary{grid-column:1/-1;background:#38606a}.devProjectBig .danger{background:#713b47}.devProjectNote{padding:9px;border:1px solid rgba(99,230,255,.14);border-radius:9px;background:rgba(99,230,255,.05);color:#cbd9dd;font-size:10px;line-height:1.4}
    #devPanel #devZoneList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:260px;overflow:auto}.devZoneChip{border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:9px;padding:9px 10px;cursor:pointer;text-align:left;min-width:0}.devZoneChip b,.devZoneChip span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devZoneChip span{font-size:9px;color:#a99bb3;margin-top:3px}.devZoneChip.active{outline:2px solid #63e6ff;background:#385a64}.devZoneBadges{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.devZoneBadges span{background:#30283a;border:1px solid rgba(255,255,255,.1);border-radius:999px;padding:5px 8px;color:#bfcbd0;font-size:9px;font-weight:800}.devView[data-dev-view="zones"] label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc;font-size:11px;font-weight:700}.devView[data-dev-view="zones"] input,.devView[data-dev-view="zones"] select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit}.devView[data-dev-view="zones"] input[readonly],.devView[data-dev-view="zones"] input:disabled{opacity:.62}
    #devPanel #devTerrainPalette{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.devTerrainType{display:grid;grid-template-columns:18px minmax(0,1fr);column-gap:7px;align-items:center;border:1px solid rgba(255,255,255,.12);background:#30283a;color:#fff;border-radius:9px;padding:8px;text-align:left;cursor:pointer;min-width:0}.devTerrainType.active{outline:2px solid #63e6ff;background:#385a64}.devTerrainSwatch{grid-row:1/3;width:18px;height:36px;border-radius:5px;border:1px solid rgba(255,255,255,.22)}.devTerrainType b,.devTerrainType small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devTerrainType small{font-size:9px;color:#a99bb3}.devView[data-dev-view="terrain"] label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc;font-size:11px;font-weight:700}.devView[data-dev-view="terrain"] input,.devView[data-dev-view="terrain"] select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit}.devView[data-dev-view="terrain"] input[readonly]{opacity:.62}
    #devPanel .devContentTypes{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.devContentTypes button,.devContentActions button,.devWideButton{border:1px solid rgba(255,255,255,.14);background:#5a4869;color:#fff;border-radius:8px;padding:8px 10px;font-weight:800;cursor:pointer}.devContentTypes button.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel #devContentList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:250px;overflow:auto}.devContentChip{border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:8px;padding:8px 9px;cursor:pointer;text-align:left;min-width:0}.devContentChip b,.devContentChip span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devContentChip span{font-size:9px;color:#a99bb3;margin-top:2px}.devContentChip.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel .devContentForm label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc;font-size:11px;font-weight:700}.devContentForm input,.devContentForm select,.devContentForm textarea{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit}.devContentForm textarea{min-height:62px;resize:vertical}.devContentForm .devInlineCheck{flex-direction:row;align-items:center;background:#2b2432;padding:8px;border-radius:7px}.devContentForm .devInlineCheck input{width:auto}.devContentActions{display:flex;gap:7px;margin-top:9px}.devContentActions button{flex:1}.devContentActions .primary{background:#38606a}.devContentActions .danger{background:#713b47}.devWideButton{width:100%;margin-top:8px}
    #devPanel .devLootHeader{display:grid;grid-template-columns:1.5fr .7fr .55fr .55fr 1.15fr;gap:5px;color:#a99bb3;font-size:9px;text-transform:uppercase;margin:6px 0 3px}.devLootEntry{display:grid;grid-template-columns:1.5fr .7fr .55fr .55fr .7fr .7fr auto;gap:5px;align-items:center;margin:5px 0}.devLootEntry input,.devLootEntry select{min-width:0;padding:6px}.devLootEntry label{margin:0!important;display:flex!important;flex-direction:row!important;align-items:center!important;gap:3px!important;font-size:9px!important}.devLootEntry label input{width:auto}.devLootEntry button{border:1px solid rgba(255,255,255,.12);background:#713b47;color:white;border-radius:7px;height:31px;font-weight:900}
    #devPanel #devSpawnPalette{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.devSpawnType{border:1px solid rgba(255,255,255,.12);background:#30283a;color:#fff;border-radius:9px;padding:9px;cursor:pointer;text-align:left}.devSpawnType b,.devSpawnType span{display:block}.devSpawnType span{font-size:9px;color:#a99bb3;margin-top:2px}.devSpawnType.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel #devSpawnList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:250px;overflow:auto}.devSpawnChip{border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:8px;padding:8px 9px;cursor:pointer;text-align:left;min-width:0}.devSpawnChip b,.devSpawnChip span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devSpawnChip span{font-size:9px;color:#a99bb3;margin-top:2px}.devSpawnChip.active{outline:2px solid #63e6ff;background:#385a64}
    #devPanel #devSpawnInspector label,#devPanel #devAssetInspector label,#devPanel [data-dev-view="assets"]>.devSection label{display:flex;flex-direction:column;gap:4px;margin:7px 0;color:#d7cbdc;font-size:11px;font-weight:700}#devPanel #devSpawnInspector input,#devPanel #devSpawnInspector select,#devPanel #devAssetInspector input,#devPanel #devAssetInspector select,#devPanel [data-dev-view="assets"]>.devSection select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit}
    
    #devPanel #devAssetList{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:330px;overflow:auto}.devAssetChip{display:grid;grid-template-columns:54px minmax(0,1fr);gap:8px;align-items:center;border:1px solid rgba(255,255,255,.12);background:#2e2736;color:#e9dff0;border-radius:9px;padding:6px;cursor:pointer;text-align:left;min-width:0}.devAssetChip.active{outline:2px solid #63e6ff;background:#385a64}.devAssetChip img{width:54px;height:54px;object-fit:contain;image-rendering:pixelated;background:rgba(0,0,0,.22);border-radius:6px}.devAssetChip b,.devAssetChip small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devAssetChip small{font-size:9px;color:#a99bb3;margin-top:3px}.devAssetPreview{height:180px;display:flex;align-items:center;justify-content:center;background:#18141d;border:1px solid rgba(255,255,255,.08);border-radius:10px;overflow:hidden;margin-bottom:10px}.devAssetPreview img{max-width:100%;max-height:100%;object-fit:contain;image-rendering:pixelated}.devAssetMeta{font-size:10px;color:#a99bb3;margin:-5px 0 8px}.devWideButton.primary{background:#38606a!important}
    #devPanel .devArtGuideGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:8px 0 10px}.devArtGuideCard{background:#211b27;border:1px solid rgba(255,255,255,.08);border-radius:9px;padding:8px 9px}.devArtGuideCard b{display:block;color:#f3ebf8;font-size:10px;letter-spacing:.04em;text-transform:uppercase;margin-bottom:4px}.devArtGuideCard small{display:block;color:#b9aebe;font-size:10px;line-height:1.35}.devArtPromptLayout{display:grid;grid-template-columns:1.1fr .9fr;gap:10px}.devArtPromptTextarea,#devPanel .devPromptOutput{width:100%;min-height:84px;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px;font:inherit;resize:vertical}.devPromptOutput{min-height:320px;line-height:1.4}.devPromptActions{display:flex;gap:7px;margin-top:10px}.devPromptActions button{flex:1;border:1px solid rgba(255,255,255,.12);background:#5a4869;color:#fff;border-radius:8px;padding:8px 10px;font-weight:800}.devPromptActions .primary{background:#38606a}.devArtPromptOutputWrap{display:flex;flex-direction:column}.devArtPromptForm{min-width:0}
    #devPanel #devObjectPalette{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.devCustomObjectCard{position:relative;border:1px solid rgba(255,255,255,.12);background:#2e2736;border-radius:9px;overflow:hidden}.devCustomObjectCard.active{outline:2px solid #63e6ff;background:#385a64}.devCustomObjectPlace{display:grid;grid-template-columns:56px minmax(0,1fr);gap:8px;align-items:center;width:100%;min-width:0;border:0;background:transparent;color:#fff;padding:6px 28px 6px 6px;text-align:left;cursor:pointer}.devCustomObjectPlace img,.devCustomObjectPlace canvas{width:56px;height:56px;object-fit:contain;image-rendering:pixelated;background:rgba(0,0,0,.22);border-radius:6px}.devCustomObjectPlace b,.devCustomObjectPlace small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devCustomObjectPlace small{font-size:9px;color:#a99bb3;margin-top:3px}.devCustomObjectRemove{position:absolute;right:5px;top:5px;width:22px;height:22px;border:1px solid rgba(255,255,255,.14);border-radius:6px;background:#713b47;color:#fff;font-weight:900;cursor:pointer}
    #devPanel .devHealthTop{display:flex;justify-content:space-between;gap:8px;align-items:center;margin:10px 0}.devHealthBadge,.devDirtyBadge{border-radius:999px;padding:6px 9px;font-size:10px;font-weight:900;letter-spacing:.03em}.devHealthBadge.healthy{background:rgba(113,200,115,.14);color:#9ff0a1;border:1px solid rgba(113,200,115,.32)}.devHealthBadge.warning,.devHealthBadge.stale{background:rgba(255,209,102,.12);color:#ffe29a;border:1px solid rgba(255,209,102,.28)}.devHealthBadge.error{background:rgba(219,103,118,.14);color:#ffafb9;border:1px solid rgba(219,103,118,.32)}.devHealthBadge.unknown,.devHealthBadge.checking{background:rgba(99,230,255,.10);color:#9cecff;border:1px solid rgba(99,230,255,.22)}.devDirtyBadge.dirty{background:rgba(255,209,102,.10);color:#ffe29a}.devDirtyBadge.clean{background:rgba(113,200,115,.08);color:#a4d9a6}.devHealthGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:9px 0}.devHealthGrid div{background:#2b2432;border:1px solid rgba(255,255,255,.06);border-radius:8px;padding:8px;min-width:0}.devHealthGrid span,.devHealthGrid b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.devHealthGrid span{font-size:8px;color:#a99bb3;text-transform:uppercase;letter-spacing:.06em}.devHealthGrid b{margin-top:2px;color:#f4eef7;font-size:11px}.devHealthActions button:disabled{opacity:.45;cursor:not-allowed}.devHealthIssueList{display:grid;gap:6px;margin-top:9px;max-height:280px;overflow:auto}.devHealthIssue{display:grid;grid-template-columns:24px minmax(0,1fr) auto;gap:7px;align-items:center;padding:8px;border-radius:8px;background:#2a2331;border:1px solid rgba(255,255,255,.07);font-size:10px;line-height:1.3}.devHealthIssue.error{border-color:rgba(219,103,118,.28)}.devHealthIssue.warning{border-color:rgba(255,209,102,.24)}.devHealthIcon{width:22px;height:22px;display:grid;place-items:center;border-radius:50%;font-weight:1000}.devHealthIssue.error .devHealthIcon{background:#713b47;color:#fff}.devHealthIssue.warning .devHealthIcon{background:#66532b;color:#fff8dd}.devHealthIssue button{border:1px solid rgba(255,255,255,.12);background:#4b4056;color:#fff;border-radius:7px;padding:5px 7px;font-weight:800}.devHealthClean{padding:10px;border-radius:8px;background:rgba(113,200,115,.08);color:#a8e2aa;border:1px solid rgba(113,200,115,.18);font-size:11px}
    body.devMode #pcControls{opacity:.25}
    @media (max-width:1050px){#devPanel{width:min(760px,78vw)!important}#devPanel .devTabs{grid-template-columns:repeat(4,1fr)}}
    @media (max-width:760px){#devPanel{top:6px!important;right:6px!important;width:calc(100vw - 12px)!important;height:calc(100vh - 12px)!important}#devPanel .devTabs{grid-template-columns:repeat(3,1fr)}#devPanel .devRepeatPlacement span{display:none}}
    @media(max-width:1100px){#devPanel{width:min(650px,68vw)!important}#devPanel #devObjectPalette{grid-template-columns:repeat(5,minmax(0,1fr))!important}}
    @media(max-width:760px){#devPanel .devContentTypes{grid-template-columns:repeat(2,1fr)}#devPanel .devArtGuideGrid{grid-template-columns:1fr}.devArtPromptLayout{grid-template-columns:1fr}#devPanel .devLootHeader{display:none}#devPanel .devLootEntry{grid-template-columns:1fr 1fr 1fr}#devPanel .devLootEntry select{grid-column:1/-1}#devPanel .devTabs{grid-template-columns:repeat(2,1fr)}#devPanel .devCombatGrid{grid-template-columns:repeat(2,minmax(0,1fr))}#devPanel .devStatPreview{grid-template-columns:repeat(2,minmax(0,1fr))}#devPanel{width:calc(100vw - 12px)!important;right:6px!important;top:6px!important;height:calc(100vh - 12px)!important}#devPanel #devObjectPalette{grid-template-columns:repeat(4,minmax(0,1fr))!important}#devPanel #devObjectList,#devPanel #devSelectionList{grid-template-columns:repeat(2,minmax(0,1fr))}#devPanel #devScalePanel{grid-template-columns:1fr}.devQuad{grid-template-columns:repeat(2,1fr)!important}}
  `;
  document.head.appendChild(style);
}


// Little Realm asset-pipeline validation cards.
const LR_ASSET_PIPELINE_STYLES = `
#devPanel .devAssetChecks{margin:10px 0 12px;padding:10px;background:#1b1720;border:1px solid rgba(255,255,255,.09);border-radius:9px}
#devPanel .devAssetChecksTitle{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px;color:#eee5f3;font-size:11px;text-transform:uppercase;letter-spacing:.05em}
#devPanel .devAssetChecksTitle span{padding:3px 6px;border-radius:999px;font-size:9px;font-weight:800}
#devPanel .devAssetChecksTitle span.good{background:rgba(86,199,128,.16);color:#8ee4ad;border:1px solid rgba(86,199,128,.28)}
#devPanel .devAssetChecksTitle span.warn{background:rgba(255,190,83,.14);color:#ffd27b;border:1px solid rgba(255,190,83,.28)}
#devPanel .devAssetCheck{display:grid;grid-template-columns:18px minmax(0,1fr);gap:1px 7px;align-items:center;padding:5px 0;border-top:1px solid rgba(255,255,255,.05);font-size:10px}
#devPanel .devAssetCheck>span{grid-row:1/3;width:16px;height:16px;display:flex;align-items:center;justify-content:center;border-radius:50%;font-weight:900}
#devPanel .devAssetCheck>b{color:#e7deeb}.devAssetCheck small{color:#a99bb3;font-size:9px}
#devPanel .devAssetCheck.good>span{background:rgba(86,199,128,.16);color:#8ee4ad}.devAssetCheck.warn>span{background:rgba(255,190,83,.14);color:#ffd27b}.devAssetCheck.info>span{background:rgba(99,230,255,.13);color:#8beeff}
`;
if(!document.getElementById("lrAssetPipelineStyles")){const style=document.createElement("style");style.id="lrAssetPipelineStyles";style.textContent=LR_ASSET_PIPELINE_STYLES;document.head.appendChild(style);}
