function updateVisualScaleControl(key,value){const n=visualScaleOr(value,VISUAL_SCALE[key]||1);VISUAL_SCALE[key]=Math.round(n*100)/100;if(devPanel){const out=devPanel.querySelector(`[data-scale-value="${key}"]`);if(out)out.textContent=VISUAL_SCALE[key].toFixed(2)+"×";}}
function setMobTypeDisplayHeight(key,value){if(!key||!BALANCE.mobs?.[key])return;const height=Math.round(Math.max(8,numberOr(value,BALANCE.mobs[key].displayHeight||MOB_SIZE_CLASS_HEIGHTS.medium)));BALANCE.mobs[key].displayHeight=height;const nearest=nearestMobSizeClass(height),preset=mobSizeClassHeight(nearest);BALANCE.mobs[key].sizeClass=Math.abs(height-preset)<=1?nearest:"custom";refreshMobTemplatesFromBalance?.();refreshDeveloperMobPanel();}
function selectDeveloperMobType(key){if(!BALANCE.mobs?.[key])return;const match=mobs.find(m=>mobTypeScaleKey(m)===key)||{spawnType:key,template:{configKey:key},boss:!!BALANCE.mobs[key].boss,alive:false};devSelectedMob=match;devCombatMobType=key;devSelected=null;devSelectedNpc=null;devSelectedRemnant=null;setDeveloperTab("scale");refreshDeveloperPanel();}
function refreshDeveloperMobPanel(){
  if(!devPanel)return;const panel=devPanel.querySelector("#devMobScalePanel");if(!panel)return;const key=mobTypeScaleKey(devSelectedMob),available=Object.keys(BALANCE.mobs||{});
  if(!key)panel.innerHTML='<div class="devEmpty">Click a mob in the world or choose a mob type below. World height belongs to each mob definition in Content.</div><div id="devMobTypeChips"></div>';
  else{const count=mobs.filter(m=>mobTypeScaleKey(m)===key).length,rec=BALANCE.mobs?.[key]||{},value=Math.max(8,numberOr(rec.displayHeight,mobSizeClassHeight(rec.sizeClass))),relative=mobRelativePlayerScale(value),canDrag=!!devSelectedMob?.alive;panel.innerHTML=`<div class="devMobSelectedTitle">${devContentEscape(mobTypeScaleLabel(key))}</div><div class="devMobMeta">Affects all ${count} ${devContentEscape(mobTypeScaleLabel(key))} spawn${count===1?"":"s"}. Source image resolution no longer changes this world size.</div><div class="devScaleControl"><div class="devScaleTop"><span>${devContentEscape(mobTypeScaleLabel(key))} visible height</span><span id="devSelectedMobScaleValue">${Math.round(value)}px • ${relative.toFixed(2)}× player</span></div><input id="devSelectedMobScale" type="range" min="8" max="120" step="1" value="${value}"></div><button id="devEditMobVisualSize" class="devSizeEditButton${devSizeEditing?" active":""}" ${canDrag?"":"disabled"}>${devSizeEditing?"Finish Visual Size":"Edit Mob Size Visually"}</button><div class="devSizeEditHelp">${canDrag?(devSizeEditing?"Drag a blue corner around the selected live mob. Mob proportions stay locked, and the new height applies to every mob of this type.":"Resize this mob directly in the world. The change applies to the whole mob type, not just this spawn."):"Click a live mob of this type in the world first to use drag-to-resize."}</div><div class="devRow"><button id="devResetMobScale">Reset ${devContentEscape(mobTypeScaleLabel(key))}</button></div><div id="devMobTypeChips"></div>`;panel.querySelector("#devSelectedMobScale").oninput=e=>setMobTypeDisplayHeight(key,e.target.value);panel.querySelector("#devEditMobVisualSize")?.addEventListener("click",()=>setDeveloperSizeEditing(!devSizeEditing));panel.querySelector("#devResetMobScale").onclick=()=>{BALANCE.mobs[key].displayHeight=mobTypeFallbackHeight(key);BALANCE.mobs[key].sizeClass=DEV_PROJECT_BALANCE?.mobs?.[key]?.sizeClass||nearestMobSizeClass(BALANCE.mobs[key].displayHeight);refreshMobTemplatesFromBalance?.();refreshDeveloperMobPanel();devSetStatus(`${mobTypeScaleLabel(key)} reset to ${Math.round(BALANCE.mobs[key].displayHeight)}px world height`);};}
  const chips=panel.querySelector("#devMobTypeChips");if(chips)for(const type of available){const b=document.createElement("button");b.className="devMobTypeChip"+(type===key?" active":"");b.textContent=mobTypeScaleLabel(type);b.onclick=()=>selectDeveloperMobType(type);chips.appendChild(b);}
}
function resetVisualScale(){Object.assign(VISUAL_SCALE,PROJECT_VISUAL_SCALE);Object.assign(LOOT_REMNANT_VISUAL,PROJECT_LOOT_REMNANT_VISUAL);for(const [id,mob] of Object.entries(BALANCE.mobs||{}))if(DEV_PROJECT_BALANCE?.mobs?.[id]){mob.displayHeight=Math.max(8,numberOr(DEV_PROJECT_BALANCE.mobs[id].displayHeight,mobSizeClassHeight(DEV_PROJECT_BALANCE.mobs[id].sizeClass)));mob.sizeClass=DEV_PROJECT_BALANCE.mobs[id].sizeClass||nearestMobSizeClass(mob.displayHeight);}refreshMobTemplatesFromBalance?.();if(!devPanel)return;devPanel.querySelectorAll("[data-scale-key]").forEach(input=>{input.value=VISUAL_SCALE[input.dataset.scaleKey];updateVisualScaleControl(input.dataset.scaleKey,input.value);});refreshDeveloperMobPanel();devSetStatus("Visual scale reset to project settings");}
