const DEV_UI_PREFS_KEY="littleRealmBuilderUiV746";
function developerUiPrefs(){try{return JSON.parse(localStorage.getItem(DEV_UI_PREFS_KEY)||"{}")||{};}catch{return {};}}
function developerSaveUiPrefs(prefs){try{localStorage.setItem(DEV_UI_PREFS_KEY,JSON.stringify(prefs||{}));}catch{}}
function developerSectionKey(section){const view=section.closest(".devView")?.dataset?.devView||"builder",title=section.querySelector(":scope > .devSectionTitle"),label=(title?.childNodes?.[0]?.textContent||title?.textContent||"section").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return `${view}:${label}`;}
function developerSetSectionCollapsed(section,collapsed,{save=true}={}){if(!section)return;section.classList.toggle("collapsed",!!collapsed);const button=section.querySelector(":scope > .devSectionTitle .devCollapseToggle");if(button){button.textContent=collapsed?"▸":"▾";button.setAttribute("aria-expanded",collapsed?"false":"true");}if(save){const prefs=developerUiPrefs(),collapsedMap={...(prefs.collapsed||{})};collapsedMap[developerSectionKey(section)]=!!collapsed;prefs.collapsed=collapsedMap;developerSaveUiPrefs(prefs);}}
function developerInitCollapsibleSections(root=devPanel){if(!root)return;const prefs=developerUiPrefs(),saved=prefs.collapsed||{};root.querySelectorAll(".devSection").forEach(section=>{const title=section.querySelector(":scope > .devSectionTitle");if(!title||title.querySelector(".devCollapseToggle"))return;const key=developerSectionKey(section),fallback=section.dataset.defaultCollapsed==="true",collapsed=Object.prototype.hasOwnProperty.call(saved,key)?!!saved[key]:fallback;const button=document.createElement("button");button.type="button";button.className="devCollapseToggle";button.title="Collapse / expand section";button.onclick=event=>{event.stopPropagation();developerSetSectionCollapsed(section,!section.classList.contains("collapsed"));};title.appendChild(button);title.classList.add("collapsible");title.onclick=event=>{if(event.target.closest("button,input,select,a"))return;developerSetSectionCollapsed(section,!section.classList.contains("collapsed"));};developerSetSectionCollapsed(section,collapsed,{save:false});});}
function developerInitPanelResize(root=devPanel){if(!root||root.querySelector(".devResizeHandle"))return;const prefs=developerUiPrefs(),saved=Number(prefs.panelWidth);if(Number.isFinite(saved)&&saved>420)root.style.setProperty("width",`${Math.min(saved,Math.max(460,window.innerWidth-24))}px`,"important");const handle=document.createElement("div");handle.className="devResizeHandle";handle.title="Drag to resize World Builder";root.appendChild(handle);let startX=0,startW=0;const move=event=>{const max=Math.max(460,window.innerWidth-24),next=Math.max(460,Math.min(max,startW+(startX-event.clientX)));root.style.setProperty("width",`${next}px`,"important");};const up=()=>{window.removeEventListener("pointermove",move,true);window.removeEventListener("pointerup",up,true);const prefsNow=developerUiPrefs();prefsNow.panelWidth=Math.round(root.getBoundingClientRect().width);developerSaveUiPrefs(prefsNow);};handle.addEventListener("pointerdown",event=>{event.preventDefault();startX=event.clientX;startW=root.getBoundingClientRect().width;window.addEventListener("pointermove",move,true);window.addEventListener("pointerup",up,true);});}
function developerInitWorkflowUi(root=devPanel){developerEnsureWorkflowStyles();developerInitCollapsibleSections(root);developerInitPanelResize(root);}
function developerBindSearchInput(selector,refresh){const input=devPanel?.querySelector(selector);if(!input||input.dataset.searchBound)return;input.dataset.searchBound="1";input.addEventListener("input",()=>refresh?.());}
function developerEnsureWorkflowStyles(){if(document.getElementById("lrWorkflowUiStyles"))return;const style=document.createElement("style");style.id="lrWorkflowUiStyles";style.textContent=`
#devPanel .devSectionTitle.collapsible{display:flex;align-items:center;gap:8px;cursor:pointer;user-select:none}#devPanel .devSectionTitle.collapsible>.devTitleCount{margin-left:auto}#devPanel .devCollapseToggle{margin-left:auto!important;flex:0 0 auto;border:0!important;background:transparent!important;color:#bca8c8!important;padding:0 3px!important;font-size:15px!important;line-height:1!important;cursor:pointer}#devPanel .devSection.collapsed{padding-bottom:7px}#devPanel .devSection.collapsed>:not(.devSectionTitle){display:none!important}
#devPanel .devSearchInput{width:100%;background:#18141d;color:#fff;border:1px solid #594b62;border-radius:8px;padding:8px 10px;margin:0 0 8px;font:inherit}#devPanel .devSearchInput:focus{outline:2px solid rgba(99,230,255,.5);border-color:#63e6ff}
#devPanel .devMasterDetail{display:grid;grid-template-columns:minmax(260px,.9fr) minmax(320px,1.1fr);gap:10px;align-items:start}#devPanel .devMasterPane,#devPanel .devDetailPane{min-width:0}#devPanel .devMasterDetail>.devMasterPane>.devSection,#devPanel .devMasterDetail>.devDetailPane>.devSection{margin-bottom:10px}#devPanel .assetsLayout #devAssetList{grid-template-columns:1fr;max-height:480px}#devPanel .assetsLayout .devDetailPane>.devSection{max-height:610px;overflow:auto}#devPanel .terrainLayout .devDetailPane>.devSection:first-child{max-height:610px;overflow:auto}#devPanel .terrainLayout #devTerrainPalette{max-height:360px;overflow:auto}
#devPanel .devImportBar{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:9px;align-items:end}#devPanel .devImportBar label{display:flex;flex-direction:column;gap:4px;color:#d7cbdc;font-size:11px;font-weight:700}#devPanel .devImportBar select{width:100%;background:#1c1821;color:#fff;border:1px solid #594b62;border-radius:7px;padding:8px}#devPanel .devImportBar button{border:1px solid rgba(255,255,255,.14);background:#38606a;color:#fff;border-radius:8px;padding:9px 13px;font-weight:900;white-space:nowrap}.devImportResult{margin-top:9px;padding:9px 10px;border:1px solid rgba(86,199,128,.25);background:rgba(86,199,128,.08);border-radius:9px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 10px;align-items:center}.devImportResult.warn{border-color:rgba(255,190,83,.28);background:rgba(255,190,83,.07)}.devImportResult b,.devImportResult span{display:block}.devImportResult span{font-size:10px;color:#b9aebe}.devImportResult>div{grid-column:2;grid-row:1/3;display:flex;gap:6px}.devImportResult button{border:1px solid rgba(255,255,255,.12);background:#4f405c;color:#fff;border-radius:7px;padding:6px 8px;font-size:10px;font-weight:800}

#devPanel .devCameraBar{display:grid;grid-template-columns:auto minmax(130px,1fr);gap:7px 10px;align-items:center;padding:7px 10px;border-bottom:1px solid rgba(255,255,255,.08);background:#18141d}#devPanel .devCameraModes,#devPanel .devCameraActions{display:flex;gap:5px;flex-wrap:wrap}#devPanel .devCameraModes button,#devPanel .devCameraActions button{border:1px solid rgba(255,255,255,.12);background:#2a2230;color:#ddd;border-radius:7px;padding:6px 8px;font-size:10px;font-weight:800}#devPanel .devCameraModes button.active{background:#315e69;border-color:#63e6ff;color:#fff}#devPanel .devCameraActions{grid-column:1/3}.devCameraReadout{justify-self:end;color:#8beeff;font-size:10px;font-weight:900;letter-spacing:.06em}.devCameraActions button.primary{background:#3c6a55!important;color:#fff!important}.devCameraActions button:disabled{opacity:.4;cursor:not-allowed}
#devPanel .audioLayout #devAudioList{max-height:440px;overflow:auto;display:grid;gap:6px}#devPanel .devAudioCard{width:100%;display:grid;grid-template-columns:30px minmax(0,1fr) 30px;gap:8px;align-items:center;text-align:left;background:#2b2331;color:#fff;border:1px solid #4c4055;border-radius:9px;padding:7px 8px}#devPanel .devAudioCard.active{background:#315e69;border-color:#63e6ff}#devPanel .devAudioCard b,#devPanel .devAudioCard small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#devPanel .devAudioCard small{color:#ae9fb5;font-size:9px;margin-top:2px}#devPanel .devAudioIcon{font-size:18px;text-align:center;color:#8beeff}#devPanel .devAudioCardPlay{display:grid;place-items:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.09)}#devPanel #devAudioSetList{display:grid;gap:6px;margin-top:8px;max-height:300px;overflow:auto}#devPanel .devAudioSetCard{display:flex;justify-content:space-between;gap:8px;align-items:center;text-align:left;background:#2b2331;color:#fff;border:1px solid #4c4055;border-radius:8px;padding:8px}#devPanel .devAudioSetCard.active{background:#315e69;border-color:#63e6ff}#devPanel .devAudioSetCard small{color:#ae9fb5}#devPanel .devAudioSetClips{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin:8px 0;max-height:320px;overflow:auto}#devPanel .devAudioClipCheck{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:6px;background:#211b26;border:1px solid #44384c;border-radius:7px;padding:6px}#devPanel .devAudioClipCheck button{padding:3px 6px}#devPanel .devAudioEventRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;align-items:end;margin-bottom:6px}#devPanel .devAudioEventRow label{display:flex;flex-direction:column;gap:3px}#devPanel .devAudioEventRow select{width:100%}
#devPanel .devResizeHandle{position:absolute;z-index:20;left:-3px;top:58px;bottom:18px;width:8px;cursor:ew-resize}#devPanel .devResizeHandle:hover:after{content:"";position:absolute;left:3px;top:0;bottom:0;width:2px;background:#63e6ff;border-radius:2px}
#devPanel .devHealthIssue.advisory{border-color:rgba(99,230,255,.18);opacity:.86}#devPanel .devHealthIssue.advisory .devHealthIcon{background:rgba(99,230,255,.13);color:#8beeff}
@media(max-width:900px){#devPanel .devMasterDetail{grid-template-columns:1fr}#devPanel .devResizeHandle{display:none}#devPanel .assetsLayout .devDetailPane>.devSection,#devPanel .terrainLayout .devDetailPane>.devSection:first-child{max-height:none;overflow:visible}.devImportResult{grid-template-columns:1fr}.devImportResult>div{grid-column:1;grid-row:auto}}
`;document.head.appendChild(style);}
