const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
global.window=global;
eval(fs.readFileSync(path.join(ROOT,'config','game-balance.js'),'utf8'));
if(!global.LR_BALANCE) throw new Error('LR_BALANCE missing');
if(global.LR_BALANCE.player.startingGold !== 0) throw new Error('startingGold should be 0 in v17 baseline');
const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
if(!index.includes('./js/runtime-loader.js')) throw new Error('runtime loader missing from index');
const loader=fs.readFileSync(path.join(ROOT,'js','runtime-loader.js'),'utf8');
if(!loader.includes('game-balance.js", true')) throw new Error('balance config not cache-busted');
if(!loader.includes('keybinds.js", true')) throw new Error('keybind config not cache-busted');
if(!loader.includes('items.js", true')) throw new Error('item config not cache-busted');
if(!loader.includes('loot-tables.js", true')) throw new Error('loot-table config not cache-busted');
if(!loader.includes('visual-settings.js", true')) throw new Error('visual config not cache-busted');
const itemCfg=fs.readFileSync(path.join(ROOT,'config','items.js'),'utf8');
const itemSandbox={}; itemSandbox.window=itemSandbox; require('vm').runInNewContext(itemCfg,itemSandbox);
if(itemSandbox.LR_ITEMS?.slimeGel?.name!=='Slime Gel') throw new Error('Slime Gel item definition missing');
if(itemSandbox.LR_ITEMS.slimeGel.icon!=='./assets/items/slime-gel.png') throw new Error('Slime Gel icon path mismatch');
if(!fs.existsSync(path.join(ROOT,'assets','items','slime-gel.png'))) throw new Error('Slime Gel artwork missing');
const lootCfg=fs.readFileSync(path.join(ROOT,'config','loot-tables.js'),'utf8');
const lootSandbox={}; lootSandbox.window=lootSandbox; require('vm').runInNewContext(lootCfg,lootSandbox);
const slimeGelDrop=lootSandbox.LR_LOOT_TABLES?.slime?.find(entry=>entry.itemId==='slimeGel');
if(!slimeGelDrop||slimeGelDrop.chancePercent!==70||slimeGelDrop.minQty!==1||slimeGelDrop.maxQty!==2) throw new Error('Slime Gel loot entry mismatch');
const visualCfg=fs.readFileSync(path.join(ROOT,'config','visual-settings.js'),'utf8');
const visualSandbox={}; visualSandbox.window=visualSandbox; require('vm').runInNewContext(visualCfg,visualSandbox);
if(!visualSandbox.LR_VISUAL?.mobTypes?.wolf) throw new Error('per-mob visual settings missing');
const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
if(!sw.includes('cache:"no-store"')) throw new Error('service worker config fetch is not no-store');
console.log('PASS live config test');
