/*
  Little Realm starter-zone placed objects.
  This file is generated by Developer Mode -> Export Layout.
  Coordinates and properties can also be edited by hand if desired.
*/
window.LR_WORLD_OBJECTS = [
  {id:"town-well",type:"well",x:390,y:316,solid:true,hitbox:{x:8,y:39,w:46,h:20},interactable:true,label:"Town Well",container:false,capacity:0},
  {id:"town-notice",type:"notice",x:652,y:566,solid:true,hitbox:{x:13,y:42,w:24,h:14},interactable:true,label:"Town Notice Board",container:false,capacity:0},
  {id:"town-market-red",type:"marketRed",x:200,y:318,solid:true,hitbox:{x:5,y:40,w:42,h:14},interactable:true,label:"Market Stall",container:false,capacity:0},
  {id:"town-market-blue",type:"marketBlue",x:290,y:322,solid:true,hitbox:{x:5,y:39,w:42,h:13},interactable:true,label:"Market Stall",container:false,capacity:0},
  {id:"town-crate",type:"crate",x:522,y:414,solid:true,hitbox:{x:4,y:26,w:36,h:16},interactable:false,label:"Crate",container:false,capacity:0},
  {id:"town-barrel",type:"barrel",x:550,y:412,solid:true,hitbox:{x:7,y:29,w:28,h:17},interactable:false,label:"Barrel",container:false,capacity:0},
  {id:"town-bench",type:"bench",x:412,y:606,solid:true,hitbox:{x:4,y:19,w:44,h:10},interactable:false,label:"Bench",container:false,capacity:0},
  {id:"town-mailbox",type:"mailbox",x:728,y:290,solid:true,hitbox:{x:11,y:35,w:12,h:10},interactable:true,label:"Mailbox",container:false,capacity:0},
  {id:"town-lamp-west",type:"lamppost",x:268,y:258,solid:true,hitbox:{x:14,y:48,w:10,h:11},interactable:false,label:"Lamp",container:false,capacity:0},
  {id:"town-lamp-east",type:"lamppost",x:610,y:260,solid:true,hitbox:{x:14,y:48,w:10,h:11},interactable:false,label:"Lamp",container:false,capacity:0},
  {id:"town-flowers-a",type:"flowerBoxA",x:394,y:280,solid:false,hitbox:{x:3,y:21,w:44,h:8},interactable:false,label:"Flower Box",container:false,capacity:0},
  {id:"town-flowers-b",type:"flowerBoxB",x:674,y:276,solid:false,hitbox:{x:3,y:21,w:44,h:8},interactable:false,label:"Flower Box",container:false,capacity:0},

  {id:"farm-hay",type:"hay",x:264,y:1240,solid:true,hitbox:{x:5,y:27,w:40,h:14},interactable:false,label:"Hay Bale",container:false,capacity:0},
  {id:"farm-haystack",type:"haystack",x:412,y:1224,solid:true,hitbox:{x:8,y:40,w:40,h:17},interactable:false,label:"Haystack",container:false,capacity:0},
  {id:"farm-trough",type:"trough",x:524,y:1488,solid:true,hitbox:{x:4,y:22,w:52,h:13},interactable:false,label:"Water Trough",container:false,capacity:0},
  {id:"farm-scarecrow",type:"scarecrow",x:274,y:1290,solid:true,hitbox:{x:15,y:49,w:14,h:14},interactable:false,label:"Scarecrow",container:false,capacity:0},
  {id:"farm-cart",type:"cart",x:530,y:1290,solid:true,hitbox:{x:6,y:28,w:50,h:15},interactable:false,label:"Farm Cart",container:false,capacity:0},
  {id:"farm-sacks",type:"sacks",x:210,y:1176,solid:true,hitbox:{x:5,y:31,w:38,h:14},interactable:false,label:"Feed Sacks",container:false,capacity:0},
  {id:"farm-bucket",type:"bucket",x:594,y:1434,solid:false,hitbox:{x:8,y:22,w:15,h:11},interactable:false,label:"Bucket",container:false,capacity:0},
  {id:"farm-crops",type:"crops",x:264,y:1414,w:90,h:82,solid:false,hitbox:{x:0,y:0,w:90,h:82},interactable:false,label:"Crops",container:false,capacity:0},

  {id:"slime-sign",type:"signpost",x:1110,y:514,solid:true,hitbox:{x:14,y:44,w:14,h:11},interactable:false,label:"Signpost",container:false,capacity:0},
  {id:"slime-mushrooms",type:"mushrooms",x:1676,y:280,solid:false,hitbox:{x:5,y:23,w:26,h:10},interactable:false,label:"Mushrooms",container:false,capacity:0},
  {id:"wild-boulder",type:"boulder",x:1874,y:986,solid:true,hitbox:{x:5,y:20,w:34,h:13},interactable:false,label:"Boulder",container:false,capacity:0},
  {id:"wild-log",type:"log",x:1554,y:1554,solid:true,hitbox:{x:4,y:22,w:42,h:11},interactable:false,label:"Fallen Log",container:false,capacity:0},
  {id:"wild-flowers",type:"flowerPatch",x:1306,y:1368,solid:false,hitbox:{x:0,y:0,w:42,h:30},interactable:false,label:"Wildflowers",container:false,capacity:0},

  {id:"goblin-tent-a",type:"goblinTent",x:2116,y:322,solid:true,hitbox:{x:7,y:38,w:42,h:17},interactable:false,label:"Goblin Tent",container:false,capacity:0},
  {id:"goblin-tent-b",type:"goblinTent",x:2376,y:326,solid:true,hitbox:{x:7,y:38,w:42,h:17},interactable:false,label:"Goblin Tent",container:false,capacity:0},
  {id:"goblin-tent-c",type:"goblinTent",x:2434,y:520,solid:true,hitbox:{x:7,y:38,w:42,h:17},interactable:false,label:"Goblin Tent",container:false,capacity:0},
  {id:"goblin-fire",type:"campfire",x:2324,y:466,solid:true,hitbox:{x:8,y:28,w:28,h:11},interactable:false,label:"Campfire",container:false,capacity:0},
  {id:"goblin-totem",type:"goblinTotem",x:2244,y:260,solid:true,hitbox:{x:14,y:53,w:16,h:12},interactable:false,label:"Goblin Totem",container:false,capacity:0},
  {id:"goblin-spikes",type:"spikeBarricade",x:2144,y:648,solid:true,hitbox:{x:4,y:21,w:44,h:12},interactable:false,label:"Barricade",container:false,capacity:0},
  {id:"goblin-crate",type:"crate",x:2190,y:530,solid:true,hitbox:{x:4,y:26,w:36,h:16},interactable:false,label:"Crate",container:false,capacity:0},
  {id:"goblin-barrels",type:"barrels3",x:2568,y:466,solid:true,hitbox:{x:5,y:29,w:44,h:14},interactable:false,label:"Barrels",container:false,capacity:0},
  {id:"goblin-bones",type:"bones",x:2510,y:532,solid:false,hitbox:{x:4,y:25,w:40,h:12},interactable:false,label:"Bone Pile",container:false,capacity:0},
  {id:"goblin-chest",type:"chest",x:2340,y:348,solid:true,hitbox:{x:4,y:25,w:36,h:12},interactable:true,label:"Goblin Chest",container:true,capacity:12,contents:[]},

  {id:"next-zone-gate",type:"blockedGate",x:2264,y:1860,solid:true,hitbox:{x:0,y:14,w:150,h:48},interactable:true,label:"Blocked Next Zone",container:false,capacity:0}
];
