const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..');
const cfgSrc=fs.readFileSync(path.join(ROOT,'config','game-balance.js'),'utf8');
const box={window:{}};vm.createContext(box);vm.runInContext(cfgSrc,box,{filename:'game-balance.js'});
const balance=box.window.LR_BALANCE;
if(!balance) throw new Error('LR_BALANCE missing');
if(balance.player.startingGold!==0) throw new Error('startingGold baseline changed');
if(balance.mobs!==undefined) throw new Error('content mobs should not live in engine balance config');
const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
if(!index.includes('./js/runtime-loader.js')) throw new Error('runtime loader missing from index');
const loader=fs.readFileSync(path.join(ROOT,'js','runtime-loader.js'),'utf8');
for(const cfg of ['./config/game-balance.js','./config/keybinds.js']) if(!loader.includes(cfg)) throw new Error('engine config missing from loader: '+cfg);
for(const old of ['./config/items.js','./config/loot-tables.js','./config/npcs.js','./config/quests.js','./config/world-objects.js','./config/visual-settings.js']) if(loader.includes(old)) throw new Error('legacy content config still loaded: '+old);
if(!loader.includes('content/little-realm.project.json')||!loader.includes('loadProjectContent')) throw new Error('project content loader missing');
const shared=JSON.parse(fs.readFileSync(path.join(ROOT,'content/shared/content-library.json'),'utf8'));
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'content/little-realm.project.json'),'utf8'));
const zone=JSON.parse(fs.readFileSync(path.join(ROOT,manifest.zones.find(z=>z.id===manifest.defaultZone).pack),'utf8'));
if(shared.items?.slimeGel?.name!=='Slime Gel') throw new Error('Slime Gel item definition missing from shared content');
if(shared.items.slimeGel.icon!=='./assets/items/slime-gel.png') throw new Error('Slime Gel icon path mismatch');
if(!fs.existsSync(path.join(ROOT,'assets/items/slime-gel.png'))) throw new Error('Slime Gel artwork missing');
const slimeGelDrop=shared.lootTables?.slime?.find(entry=>entry.itemId==='slimeGel');
if(!slimeGelDrop||slimeGelDrop.chancePercent!==70||slimeGelDrop.minQty!==1||slimeGelDrop.maxQty!==2) throw new Error('Slime Gel loot entry mismatch');
if(!shared.mobs?.wolf?.spriteAsset||!shared.assets?.[shared.mobs.wolf.spriteAsset]) throw new Error('mob sprite asset relationship missing');
if(!shared.terrains||Object.keys(shared.terrains).length<1) throw new Error('Terrain Library missing');
if(!Array.isArray(zone.worldObjects)||!Array.isArray(zone.npcs)||!Array.isArray(zone.quests)||!Array.isArray(zone.mobSpawns)) throw new Error('zone-owned content missing');
for(const f of ['items.js','loot-tables.js','npcs.js','quests.js','world-objects.js','visual-settings.js']) if(fs.existsSync(path.join(ROOT,'config',f))) throw new Error('deleted content config unexpectedly exists: '+f);
const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
if(!sw.includes('cache:"no-store"')) throw new Error('service worker config/project fetch is not no-store');
console.log('PASS normalized project/config ownership test');
